name: Semantic Linting

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  semantic-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # To fetch all history for PR changes

      - name: Run semantic linting
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ai-api-key: ${{ secrets.AI_API_KEY }}
